'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EOPFiles

    '''<summary>
    '''clientFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clientFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''clientLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clientLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Boxes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Boxes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlBoxes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlBoxes As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Location As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlLocation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''SqlFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlFiles As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''GridViewFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewFiles As Global.System.Web.UI.WebControls.GridView
End Class
