'                   --
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'                   --

Option Strict On
Option Explicit On


Partial Public Class CreateRequest

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''clientFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clientFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredClientFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredClientFirstName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''clientLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clientLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredClientLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredClientLastName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''clientLastFourSSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clientLastFourSSN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredclientLastFourSSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredclientLastFourSSN As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''PriorityType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PriorityType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlPriorityTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlPriorityTypes As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''requiredPriorityType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredPriorityType As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''PurposeType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PurposeType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlPurposeTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlPurposeTypes As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''requiredPurposeType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredPurposeType As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents button As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
End Class
