'                   --
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'                   --

Option Strict On
Option Explicit On


Partial Public Class UsersRequests

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''clientFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clientFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''clientLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clientLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequestDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequestDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredRequestDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredRequestDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ListRequestor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListRequestor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlRequestor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlRequestor As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''PriorityType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PriorityType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlPriorityTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlPriorityTypes As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''PurposeType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PurposeType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlPurposeTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlPurposeTypes As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ButtonExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonExport As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''SqlUsersRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlUsersRequests As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''GridViewUsersRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewUsersRequests As Global.System.Web.UI.WebControls.GridView
End Class
