'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreateBox

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''BoxNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BoxNumber As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''requiredBoxNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredBoxNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BoxYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BoxYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''requiredBoxYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredBoxYear As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''AnticipatedDeliveryToWarehouseDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnticipatedDeliveryToWarehouseDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredAnticipatedDeliveryToWarehouseDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredAnticipatedDeliveryToWarehouseDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BoxLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BoxLocation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlLocation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''requiredBoxLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredBoxLocation As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
End Class
